version: '3.8'
services:

  be_dev_debug:
    build: 
      context: .
      dockerfile: ./dockerfile.dev.debug
    environment:
      - PGSQL_HOST=pgdb
      - PGSQL_USERNAME=postgres
      - PGSQL_PASSWORD=postgres
      - PGSQL_DB_NAME=auth
      - PGSQL_PORT=5432
      - JWT_SECRET=02a03eb5c54989b772f4f162f2d025d8
      - JWT_REF_SECRET=50c75233bf3687d607139f9e23e81d84
    volumes:
      - .:/app
    ports:
      - '8898:8898'
      - '8899:8899'

  be_test_debug:
    build: 
      context: .
      dockerfile: ./dockerfile.dev.test.debug
    volumes:
      - ".:/app"
    ports:
      - '8897:8897'
  
